cd /images
mkdir debian-apache
cd debian-apache/
mkdir site
cd site/
wget http://site1368633667.hospedagemdesites.ws/site1.zip
unzip site1.zip
rm site1.zip
tar -czf site.tar ./
cp site.tar ../

rm -Rf site 

nano Dockerfile



FROM debian

RUN 

apt-get update && apt-get install -y apache2 && apt-get clean

ENV APACHE_LOCK_DIR="var/lock"
ENV APACHE_PID_FILE=""
ENV APACHE_RUN_USER=""
ENV APACHE_RUN_GROUP=""
ENV APACHE_LOG_DIR=""

ADD site.tar /var/www/html

LABEL description = "Apache webserver 1.0"

VOLUME /var/www/html

EXPOSE 80

ENTRYPOINT ["/usr/sbin/apachectl"]

cmd ["-D", "FOREGROUND"]

final do dockerfile

docker image build -t debian-apache:1.0 .

docker run -dti -p 80:80 --name meu-apache debian-apache:1.0
